name: sync-88-AutoSignMachine

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 0-16,22-23 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.repository == 'ggsimida101/88-AutoSignMachine main'

    steps:
    - name: Init Build Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E rm -rf /etc/apt/sources.list.d
        sudo -E apt-get update -y && apt-get install -y build-essential git git-core curl wget && apt-get clean -y
        git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'

    - name: Clone Master
      run: |
        git clone -b main simo8102/88-AutoSignMachine main

    - name: Push Main
      uses: ad-m/github-push-action@master
      with:
        directory: main
        github_token: ${{ secrets.PAT }}
        branch: main

    - name: Delete Workflow Runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 0
